services:
  nllb-base:
    image: resumed-nllb-base:latest
    build:
      context: .
      dockerfile: Dockerfile.base

  nllb-pl-en:
    image: resumed-nllb:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8888:8080"]
