name: Build Base Image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    outputs:
      version:
        description: "Version of the built base image"
        value: ${{ jobs.build-base.outputs.version }}
  workflow_dispatch:
    inputs:
      force:
        description: 'Force rebuild even if poetry files did not change'
        required: false
        default: 'false'

jobs:
  check-base-changed:
    uses: ./.github/workflows/base-changed.yml

  get-version:
    uses: ./.github/workflows/base-current.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  build-base:
    name: Build and Push Base Image
    needs: [check-base-changed, get-version]
    if: inputs.force == 'true' || needs.check-base-changed.outputs.changed == 'true'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest base image version
        id: set_version
        run: |
          current=${{ needs.get-version.outputs.version }}
          next=$(($current + 1))
          echo "version=$next" >> $GITHUB_OUTPUT
      
      - name: Print next base version
        run: echo "Current Base Image version is ${{ steps.set_version.outputs.version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/resumed-nllb-base:${{ steps.set_version.outputs.version }}
