name: Build and Push Images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

  build-base:
    name: Build and Push Base Image
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Base Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/resumed-nllb-base:${{ needs.extract-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/resumed-nllb-base:latest

  build-app:
    name: Build and Push App Image
    needs: [extract-version, build-base]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push App Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BASE_IMAGE_TAG=${{ needs.extract-version.outputs.version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/resumed-nllb:${{ needs.extract-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/resumed-nllb:latest
